# Generated by Django 3.1.7 on 2021-11-15 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletePayment',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=500)),
                ('Emailaddress', models.EmailField(max_length=254)),
                ('Age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(65), django.core.validators.MinValueValidator(18)])),
                ('batch', models.IntegerField()),
                ('payment', models.IntegerField()),
            ],
        ),
    ]
